---
title: "Adult Income Exploratory Data Analysis"
author: "Taylor Bonar"
date: "7/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(naniar)
library(GGally)
library(funModeling)
library(Hmisc)

setwd(".")

basic_eda <- function(data) # Sample Function Source: https://blog.datascienceheroes.com/exploratory-data-analysis-in-r-intro/
{
  glimpse(data)
  print(status(data))
  freq(data) 
  print(profiling_num(data))
  plot_num(data)
  describe(data)
}

```

```{r data-cleanup}

adult_income <- read.csv(file = "../data/adult.data", header=FALSE, quote="", na.strings = "?")

colnames(adult_income) <- c("age","workclass","fnlwgt","education","education_num","marital_status","occupation","relationship","race","sex","capital_gain","capital_loss","hours_per_week","native_country","income_status")

sum(complete.cases(adult_income)) # Complete rows are 30162
sum(!complete.cases(adult_income)) # Missing 2399 

colSums(is.na(adult_income)) # Counts the number of NAs for each column - majority in occupation, workclass, and native_country

# Transform some character classes into a factor class
adult_income$workclass <- factor(adult_income$workclass)
adult_income$education <- factor(adult_income$education)
adult_income$marital_status <- factor(adult_income$marital_status)
adult_income$occupation <- factor(adult_income$occupation)
adult_income$relationship <- factor(adult_income$relationship)
adult_income$race <- factor(adult_income$race)
adult_income$sex <- factor(adult_income$sex)
adult_income$native_country <- factor(adult_income$native_country)
adult_income$income_status <- factor(adult_income$income_status)

```

```{r data-inspection}
basic_eda(adult_income) # initial look at data

vis_miss(adult_income, cluster = F) + # Without aggregating observations
  labs(title = "NAs in Adult Income from Census of 1996 ") +
  theme(axis.text.x = element_text(angle=90))

# Those missing a work class and occupation may be overlapping, though overall only 0.9% of data is missing

gg_miss_upset(adult_income) # Here we can see an aggregation via upset plot (reference: https://www.youtube.com/watch?v=-IfF2wGw7Qk )

ggcorr(data=adult_income, label = T, nbreaks=5, label_size = 3, hjust = 0.9, size = 3, layout.exp = 4) +
  labs(title = "Multicollinearity of Variables (Pairwise / Pearson's correlation)")
# No major collinearity variables for continuous variables 
```

# Logistic Regression Assumptions
1. Response Variable is __binary__
2. Observations are __independent__
3. No multicollinearity among explanatory variables
4. No extreme outliers
5. There is a linear relationship between explanatory variables jand the logit of the response variable
6. The sample size is sufficiently large


